apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: logging
data:
  filebeat.yaml: |
    filebeat.inputs:
      - type: container
        paths:
          - /var/log/containers/*.log
        processors:
          - add_kubernetes_metadata:
              in_cluster: true
              matchers:
              - logs_path:
                  logs_path: "/var/log/containers/"  

    output.logstash:
      hosts: ["logstash:5044"]
